name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Check dist folder
        run: |
          pwd
          ls -la
          ls -la dist

      - name: Archive build
        run: |
          zip -r dist.zip dist

      - name: Verify zip
        run: ls -la dist.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
